<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWxacesl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWxacesl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWxacesl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWxacesl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWxacesl\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wxacesl',
    'container.build_id' => '7fad6266',
    'container.build_time' => 1596239950,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWxacesl');
